//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SSHKeys struct {
	Fingerprint *string `sql:"primary_key"`
	Email       string
	CreatedAt   time.Time
}
